spring.application.name=kennel-inventory

application.relative.path=/api/dog/
image.service.base.url=https://dog.ceo
image.service.relative.path=/api/breeds/image/random
image.service.cron.expression=0 */2 * * * *

spring.jpa.defer-datasource-initialization=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
